app = "util-eyes"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000  # Changed to match Gunicorn
  force_https = true
  auto_stop_machines = true   # Allow machines to stop when idle
  auto_start_machines = true  # Start them when traffic comes
  min_machines_running = 0    # Scale to zero
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source = "util_eyes_data"
  destination = "/app/instance"  # For SQLite during development/testing
  initial_size_gb = 1

[env]
  FLASK_ENV = "production"
  FLASK_APP = "app.py"

# Note: The following secrets should be set using fly secrets:
# flyctl secrets set SECRET_KEY=your-secret-key
# 
# For PostgreSQL, set these secrets:
# flyctl secrets set DATABASE_URL=postgresql://user:password@host:5432/dbname
# flyctl secrets set POSTGRES_USER=your-postgres-user
# flyctl secrets set POSTGRES_PASSWORD=your-postgres-password
# flyctl secrets set POSTGRES_HOST=your-postgres-host

[experimental]
  enable_sleep = true  # Reduces cold starts while staying in free tier
  auto_suspend_idle_timeout = "300s"  # Sleep after 5 minutes of inactivity
  auto_suspend_max_duration = "24h"   # Max sleep duration